module Furcate
  class Leaf
    attr_reader id: untyped

    attr_reader type: untyped

    attr_reader attributes: untyped

    def create: () -> untyped

    def delete: () -> untyped

    def update: () -> untyped

    def self.find: (untyped object_id) -> Leaf

    def sha: () -> untyped

    def diff: (Leaf other_leaf) -> (:no_match | :changed | :no_change)
  end
end
