module Furcate
  class CommitDiff
    attr_reader additions: Array[Leaf]

    attr_reader deletions: Array[Leaf]

    attr_reader modifications: Array[Leaf]

    def initialize: (untyped additions, untyped deletions, untyped modifications) -> void

    def self.diff: (Commit commit, Commit other_commit) -> CommitDiff

    def same?: () -> bool

    def conflicts: (CommitDiff diff, CommitDiff other_diff) -> untyped
  end
end
