module Furcate
  class Commit
    extend Forwardable

    attr_reader parent_commit: Commit

    attr_reader leaves: Array[Leaf]

    def initialize: (Commit parent_commit, Stage stage) -> void

    def find: (String furcate_id) -> Leaf?

    def first_common_ancestor: (Commit scion_head) -> Commit

    def any_matching_keys?: (Leaf other_leaf) -> bool

    def no_matching_keys?: (Leaf other_leaf) -> bool

    def any_changed_attributes?: (Leaf other_leaf) -> bool

    private

    def find_ancestor: (Commit scion_head, Commit scion_commit, Commit rootstock_head) -> Commit
    def build_new_leaves: (Array[Leaf] leaves, Stage stage) -> Array[Leaf]
    def add: (Array[Leaf] leaves, Leaf change_leaf) -> void
    def delete: (Array[Leaf] leaves, Leaf change_leaf) -> void
    def modify: (Array[Leaf] leaves, Leaf change_leaf) -> void
  end
end
