module Furcate
  class Furcator
    extend Forwardable

    def initialize: () -> void

    def staged_changes: () -> Stage

    def commit_addition: (Leaf leaf) -> untyped

    def commit_deletion: (Leaf leaf) -> untyped

    def commit_modification: (Leaf leaf) -> untyped

    def create_and_switch_to_limb: (String limb_name) -> void

    def switch_to_limb: (String limb_name) -> void

    def find: (String furcate_id) -> Leaf?

    attr_reader head: Commit

    attr_reader references: Hash[String, Commit]

    private

    def make_commit: (?::String message) -> untyped
  end
end
