module Furcate
  class Furcator
    extend Forwardable

    def initialize: () -> void

    def create_and_switch_to_limb: (String limb_name) -> void

    def switch_to_limb: (String limb_name) -> void

    def find: (String furcate_id) -> Leaf?

    attr_reader head: Commit

    attr_reader references: Hash[String, Commit]

    def make_commit: (Change) -> Commit
  end
end
